Dev
RomanDorosinec/JavaTraining pull request #1
Opened 2016-10-04 06:59 UTC by RomanDorosinec

2016-10-04 14:27 UTC, AlexanderSoroka requested changes

2016-10-04 14:27 UTC, AlexanderSoroka commented on taskfour/src/by/dorosinets/training/quadraticequation/Runner.java
> +     * Check our arguments on the amount of numbers after the decimal point
What kind of issue are you trying to solve with this check?

2016-10-04 14:27 UTC, AlexanderSoroka commented on taskfour/src/by/dorosinets/training/quadraticequation/Runner.java
> +     * Check our arguments on the amount of numbers after the decimal point
and it's actually not valid - what if user input 10e-15 - it's around 15 numbers after decimal point but your check will definitely miss it

2016-10-04 14:27 UTC, AlexanderSoroka commented on taskfour/src/by/dorosinets/training/quadraticequation/Equation.java
> +        this.numberA = a;
what if somebody pass to this class a == NaN?

2016-10-05 10:31 UTC, AlexanderSoroka requested changes
I don't see task#5 in this pull request? Where can I take a look on it?

2016-10-05 10:31 UTC, AlexanderSoroka commented on taskfour/src/by/dorosinets/training/quadraticequation/Equation.java
> +        if (Double.isNaN(a) || Double.isNaN(b) || Double.isNaN(c)) {
So infinities are accepted values?

2016-10-05 10:31 UTC, AlexanderSoroka commented on taskfour/src/by/dorosinets/training/quadraticequation/Equation.java
> +        if (numberA == 0.0) {
Invalid double comparison

2016-10-05 13:12 UTC, RomanDorosinec commented on taskfour/src/by/dorosinets/training/quadraticequation/Equation.java
> +        if (numberA == 0.0) {
I know, but I don't have free time, chenge this mistake. I'm so sorry

2016-10-10 12:12 UTC, merged